version: "3.8"
services:
  backend:
    container_name: ikeep-backend
    build: ./backend
    image: durlavparajuli/ikeep-backend:v1
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
  frontend:
     container_name: ikeep-frontend
     build: ./frontend
     image: durlavparajuli/ikeep-frontend:v1
     env_file:
      - ./frontend/.env
     ports:
      - "5173:5173"
  database:
     container_name: mongodb
     image: mongo:jammy
     ports:
      - "27071:27017"
