version: "3.8"
services:
  database:
    container_name: mongodb
    image: mongo:jammy
    volumes:
      - ./backend/data:/data
    ports:
      - "27071:27017"

  backend:
    container_name: ikeep-backend
    build: ./backend
    image: durlavparajuli/ikeep-backend:v1
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: ikeep-frontend
    build: ./frontend
    image: durlavparajuli/ikeep-frontend:v1
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
