apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikeep-frontend-deployment
  labels:
    app: ikeep-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ikeep-frontend
  template:
    metadata:
      labels:
        app: ikeep-frontend
    spec:
      containers:
        - name: ikeep-frontend
          image: durlavparajuli/ikeep_frontend:v1
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: ikeep-frontend-service
spec:
  type: NodePort
  selector:
    app: ikeep-frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30004
