apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikeep-database-deployment
  labels:
    app: ikeep-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ikeep-database
  template:
    metadata:
      labels:
        app: ikeep-database
    spec:
      containers:
        - name: ikeep-database
          image: mongo:jammy
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: ikeep-database-service
spec:
  type: ClusterIP
  selector:
    app: ikeep-database
  ports:
    - port: 27017
      targetPort: 27017
