apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikeep-backend-deployment
  labels:
    app: ikeep-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ikeep-backend
  template:
    metadata:
      labels:
        app: ikeep-backend
    spec:
      containers:
        - name: ikeep-backend
          image: durlavparajuli/ikeep_backend:v1
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: ikeep-backend-service
spec:
  type: NodePort
  selector:
    app: ikeep-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
